from sqlalchemy.orm import Session
import models, schemas

def get_employee(db: Session):
    return db.query(models.Employee).all() # this function retrieves all employee records from the database and returns them as a list of Employee objects.
 
def get_employee_by_id(db: Session, emp_id: int):
    return(
        db
         .query(models.Employee)
         .filter(models.Employee.id== emp_id)
         .first()
    )
     
def create_employee(db: Session, employee: schemas.EmployeeCreate):
    db_employee= models.Employee(
        name= employee.name,
        email= employee.email,
        department= employee.department
    )
    db.add(db_employee) # this line adds the new employee object to the database session, marking it for insertion into the database when the session is committed.
    db.commit() # this line commits the current transaction, which means that any changes made to the database session (such as adding the new employee) will be saved to the database.
    db.refresh(db_employee)
    return db_employee # this line returns the newly created employee object, which now includes any additional fields that were generated by the database (such as the id field).


def update_employee(db: Session, emp_id: int, employee: schemas.EmployeeUpdate):
    db_employee= db.query(models.Employee).filter(models.Employee.id== emp_id).first()
    if db_employee:
        db_employee.name= employee.name
        db_employee.email= employee.email
        db_employee.department=employee.department
        
        db.commit()
        db.refresh(db_employee)
        return db_employee
    return None

def delete_employee(db: Session, emp_id: int):
    db_employee= db.query(models.Employee).filter(models.Employee.id== emp_id).first()
    if  db_employee:
         db.delete(db_employee)
         db.commit()
    return db_employee